Repository AY2324S1-CS2103T-T12-2/tp, pull requests merged in 2023-11, with the labels that each got.

#69 Add test cases for Events
  src/main/java/seedu/address/logic/commands/CommandUtil.java
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditEventCommand.java
  src/main/java/seedu/address/logic/commands/ListAllCommand.java
  src/main/java/seedu/address/logic/commands/ListEventsCommand.java
  src/main/java/seedu/address/logic/commands/RemindCommand.java
  src/main/java/seedu/address/logic/parser/EditMeetingCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RemindCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/EventDate.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteEventCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditEventCommandTest.java
  src/test/java/seedu/address/logic/commands/RemindCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteMeetingCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditMeetingCommandParserTest.java
  src/test/java/seedu/address/model/event/EventComparatorTest.java
  src/test/java/seedu/address/model/event/EventDateTest.java
  src/test/java/seedu/address/model/event/EventListTest.java
  src/test/java/seedu/address/model/event/MeetingTest.java
  src/test/java/seedu/address/testutil/EditEventDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditMeetingDescriptorBuilder.java
  src/test/java/seedu/address/testutil/MeetingBuilder.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium, severity.Medium, type.Test

#71 Fix minor bug in DG
  docs/DeveloperGuide.md
Labels: type.Bug, type.Documentation

#72 Update Person class
  src/main/java/seedu/address/logic/commands/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/DeletePersonCommand.java
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddMeetingCommandParser.java
  src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeletePersonCommandParser.java
  src/main/java/seedu/address/logic/parser/EditPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Remark.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeletePersonCommandTest.java
  src/test/java/seedu/address/logic/commands/EditEventCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddPersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeletePersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditPersonCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, priority.Low

#75 Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/leezhengjing.md
Labels: priority.High

#73 Add tests and change behavior of edit command
  docs/diagrams/CommandFlowActivityDiagram.puml
  docs/images/CommandFlowActivityDiagram.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/parser/EditPersonCommandParser.java
  src/main/java/seedu/address/model/event/Meeting.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/resources/view/EventListCard.fxml
  src/main/resources/view/ExpiredEventCard.fxml
  src/test/java/seedu/address/logic/commands/CommandUtilTest.java
  src/test/java/seedu/address/logic/commands/EditPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/ListAllCommandTest.java
  src/test/java/seedu/address/logic/commands/ListEventsCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditPersonCommandParserTest.java
  src/test/java/seedu/address/model/event/MeetingTest.java
  src/test/java/seedu/address/model/group/GroupTest.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
Labels: type.Enhancement, priority.High, type.Test

#74 Update UG and add test cases
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/nicleongyj.md
  src/main/java/seedu/address/logic/commands/RemindCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Birthday.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/RemindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/RemindCommandParserTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/BirthdayTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
Labels: type.Enhancement, priority.High, type.Documentation

#76 Update UG and DG
  .github/ISSUE_TEMPLATE/bug-report-template.md
  .github/ISSUE_TEMPLATE/user-story-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_config.yml
  docs/_sass/minima/_base.scss
  docs/diagrams/AssignGroupsSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/EventClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/RemindSequenceDiagram.puml
  docs/images/Addperson.png
  docs/images/AssignGroupsSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/DeletePerson.png
  docs/images/Editperson.png
  docs/images/EventClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/Ui.png
  docs/images/findAlexDavidResult.png
  docs/images/findFriendsResult.png
  docs/index.md
  docs/team/kurtyjlee.md
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
Labels: priority.Medium, type.Documentation

#80 Update Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/AddEventObjectDiagram.puml
  docs/images/AddEventObjectDiagram.png
Labels: priority.Low, type.Documentation

#79 Bug fix
  .github/ISSUE_TEMPLATE/bug-report-template.md
  .github/ISSUE_TEMPLATE/user-story-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  docs/_config.yml
Labels: type.Bug, priority.Medium, type.Documentation

#81 Fix typo for image
  docs/UserGuide.md
Labels: type.Bug, priority.Low

#82 v1.3 Further enhance find_all and find_event command
  src/main/java/seedu/address/logic/commands/FindAllCommand.java
  src/main/java/seedu/address/logic/commands/FindEventCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/EventNameOrGroupContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindAllCommandTest.java
  src/test/java/seedu/address/logic/commands/FindEventCommandTest.java
  src/test/java/seedu/address/logic/commands/ListAllCommandTest.java
  src/test/java/seedu/address/logic/commands/ListEventsCommandTest.java
  src/test/java/seedu/address/model/event/EventNameContainsKeywordsPredicateTest.java
Labels: type.Enhancement, priority.High

#84 Fix bugs for EventListPanel
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Bug, priority.High, severity.High

#83 Update Test Cases
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteEventCommandParser.java
  src/main/java/seedu/address/logic/parser/EditEventCommandParser.java
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/commons/core/GuiSettingsTest.java
  src/test/java/seedu/address/commons/core/LogsCenterTest.java
  src/test/java/seedu/address/commons/core/VersionTest.java
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
  src/test/java/seedu/address/logic/commands/EditEventCommandTest.java
  src/test/java/seedu/address/logic/parser/AddEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditEventCommandParserTest.java
Labels: priority.Medium, type.Test

#127 v1.4: Fix issues and update UG
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/NameTest.java
Labels: type.Bug, priority.High, type.Documentation

#129 Fix table format in UG
  docs/UserGuide.md
Labels: type.Documentation

#128 Address Issues of PE-D
  docs/UserGuide.md
  docs/images/DuplicatePersonInDifferentGroups.png
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
Labels: type.Bug, priority.Medium, type.Documentation

#132 v1.4: Hotfix for person name
  src/main/java/seedu/address/model/person/Name.java
Labels: type.Bug, priority.Low, severity.Low

#131 v1.4 Resolve bugs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
Labels: type.Bug, type.Documentation

#133 Update UG
  docs/UserGuide.md
Labels: priority.Low, severity.Low, type.Documentation

#135 Update UG to highlight edit attribute differences
  docs/UserGuide.md
  docs/team/kurtyjlee.md
  src/main/resources/view/EventListCard.fxml
Labels: priority.Low, severity.Low, type.Documentation

#136 Update person commands in UG
  docs/UserGuide.md
  docs/images/findFriendsResult.png
Labels: type.Documentation

#137 Update UG: Issue #134
  docs/UserGuide.md
  docs/team/distractedcat.md
Labels: priority.Low, type.Documentation

#139 Docs: Update UG and favicon
  docs/UserGuide.md
  docs/_includes/custom-head.html
  docs/_includes/head.html
  docs/images/favicon.png
  docs/images/favicon/android-chrome-192x192.png
  docs/images/favicon/android-chrome-512x512.png
  docs/images/favicon/apple-touch-icon.png
  docs/images/favicon/browserconfig.xml
  docs/images/favicon/favicon-16x16.png
  docs/images/favicon/favicon-32x32.png
  docs/images/favicon/favicon.ico
  docs/images/favicon/mstile-150x150.png
  docs/images/favicon/safari-pinned-tab.svg
  docs/images/favicon/site.webmanifest
  docs/team/kurtyjlee.md
Labels: priority.Low, type.Documentation

#140 Partial bug fix to find_all command
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventList.java
  src/main/java/seedu/address/model/event/EventNameOrGroupContainsKeywordsPredicate.java
Labels: type.Bug, priority.High

#143 Docs: Update documentation for event commands for UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Eventdelete.png
  docs/images/Eventfind.png
  docs/images/Findall.png
  docs/team/distractedcat.md
  docs/team/nicleongyj.md
  src/main/java/seedu/address/logic/commands/RemindCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: type.Bug, priority.High, type.Documentation

#145 v1,4 Minor bug fix
  docs/UserGuide.md
Labels: type.Documentation

#146 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/AddEventObjectDiagram.puml
  docs/images/AddEventObjectDiagram.png
Labels: type.Documentation

#147 Update DG and fix UG
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/UserGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/EditEventObjectDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/EditEventObjectDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/tutorials/TracingCode.md
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
Labels: type.Documentation

#141 Bugfix: Add UG documentation for expired event
  docs/UserGuide.md
  docs/images/ExpiredEvent.png
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/parser/EditPersonCommandParser.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/resources/view/EventListCard.fxml
Labels: type.Bug

#148 Docs: Fix minor issues
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
Labels: type.Documentation

#150 Add details for PPP
  docs/team/ken-lai.md
Labels: type.Documentation

#151 Docs: Remove duplicate documentation in DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Documentation

#152 Add details to DeveloperGuide.md
  docs/DeveloperGuide.md
  docs/diagrams/FindAllSequenceDiagram.puml
  docs/diagrams/FindEventSequenceDiagram.puml
  docs/diagrams/FindPersonSequenceDiagram.puml
  docs/diagrams/style.puml
  docs/images/FindAllSequenceDiagram.png
  docs/images/FindEventSequenceDiagram.png
  docs/images/FindPersonSequenceDiagram.png
Labels: type.Documentation

#155 Fix bugs in DG
  docs/DeveloperGuide.md
  docs/diagrams/FindAllSequenceDiagram.puml
  docs/diagrams/FindEventSequenceDiagram.puml
  docs/diagrams/FindPersonSequenceDiagram.puml
  docs/images/FindAllSequenceDiagram.png
  docs/images/FindEventSequenceDiagram.png
  docs/images/FindPersonSequenceDiagram.png
Labels: type.Bug, type.Documentation

#154 Small DG changes
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Documentation

#156 edit UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState4.puml
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState4.png
Labels: type.Documentation

#165 Fix typos
  docs/DeveloperGuide.md
Labels: type.Documentation
